import { User, Project, Task, ActivityItem, Dashboard } from './types';
import { PROJECT_COLORS } from './constants';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@company.com',
    avatar: 'https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/6844ed4a-cb52-4978-9e9a-7d94dda6a105.png',
    role: 'admin',
    joinedAt: new Date('2024-01-15'),
    isOnline: true,
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael@company.com',
    avatar: 'https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/10be0bbf-df80-47a7-80b8-dd3da2511607.png',
    role: 'member',
    joinedAt: new Date('2024-02-01'),
    isOnline: true,
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily@company.com',
    avatar: 'https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/3b2e2f06-ab16-4687-ac91-d8795fe0978d.png',
    role: 'member',
    joinedAt: new Date('2024-02-10'),
    isOnline: false,
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david@company.com',
    avatar: 'https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/e3d35718-3541-499d-8059-07d1d610a99a.png',
    role: 'viewer',
    joinedAt: new Date('2024-03-01'),
    isOnline: true,
  },
  {
    id: '5',
    name: 'Jessica Thompson',
    email: 'jessica@company.com',
    avatar: 'https://storage.googleapis.com/workspace-0f70711f-8b4e-4d94-86f1-2a93ccde5887/image/8eeb878d-0114-42e5-b339-fc3fb9dc4df7.png',
    role: 'member',
    joinedAt: new Date('2024-03-15'),
    isOnline: false,
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design new landing page',
    description: 'Create a modern, responsive landing page for the marketing campaign',
    status: 'in-progress',
    priority: 'high',
    assignee: mockUsers[1],
    reporter: mockUsers[0],
    projectId: '1',
    subtasks: [
      {
        id: '1-1',
        title: 'Create wireframes',
        completed: true,
        assignee: mockUsers[1],
        dueDate: new Date('2024-12-18'),
        createdAt: new Date('2024-12-15'),
      },
      {
        id: '1-2',
        title: 'Design mockups',
        completed: false,
        assignee: mockUsers[1],
        dueDate: new Date('2024-12-20'),
        createdAt: new Date('2024-12-15'),
      },
    ],
    comments: [],
    attachments: [],
    tags: ['design', 'ui/ux', 'marketing'],
    dueDate: new Date('2024-12-22'),
    estimatedHours: 16,
    actualHours: 8,
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-17'),
    dependencies: [],
    customFields: {},
  },
  {
    id: '2',
    title: 'Implement user authentication',
    description: 'Set up secure user login and registration system',
    status: 'todo',
    priority: 'urgent',
    assignee: mockUsers[2],
    reporter: mockUsers[0],
    projectId: '2',
    subtasks: [],
    comments: [],
    attachments: [],
    tags: ['backend', 'security', 'auth'],
    dueDate: new Date('2024-12-25'),
    estimatedHours: 24,
    createdAt: new Date('2024-12-16'),
    updatedAt: new Date('2024-12-16'),
    dependencies: [],
    customFields: {},
  },
  {
    id: '3',
    title: 'Create brand guidelines',
    description: 'Develop comprehensive brand guidelines document',
    status: 'review',
    priority: 'medium',
    assignee: mockUsers[4],
    reporter: mockUsers[0],
    projectId: '3',
    subtasks: [],
    comments: [],
    attachments: [],
    tags: ['design', 'branding', 'documentation'],
    dueDate: new Date('2024-12-28'),
    estimatedHours: 12,
    actualHours: 10,
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-17'),
    dependencies: [],
    customFields: {},
  },
  {
    id: '4',
    title: 'Setup project infrastructure',
    description: 'Configure CI/CD pipeline and development environment',
    status: 'done',
    priority: 'high',
    assignee: mockUsers[1],
    reporter: mockUsers[0],
    projectId: '2',
    subtasks: [],
    comments: [],
    attachments: [],
    tags: ['devops', 'infrastructure', 'automation'],
    dueDate: new Date('2024-12-15'),
    estimatedHours: 20,
    actualHours: 18,
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-14'),
    dependencies: [],
    customFields: {},
  },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Complete redesign of company website with modern UI/UX',
    color: PROJECT_COLORS[0],
    status: 'active',
    priority: 'high',
    progress: 65,
    startDate: new Date('2024-12-01'),
    endDate: new Date('2024-12-30'),
    owner: mockUsers[0],
    team: [mockUsers[0], mockUsers[1], mockUsers[2]],
    tasks: mockTasks.filter(task => task.projectId === '1'),
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-12-17'),
    template: 'design',
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Build native mobile application for iOS and Android',
    color: PROJECT_COLORS[1],
    status: 'active',
    priority: 'urgent',
    progress: 30,
    startDate: new Date('2024-12-01'),
    endDate: new Date('2025-02-28'),
    owner: mockUsers[0],
    team: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[3]],
    tasks: mockTasks.filter(task => task.projectId === '2'),
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-12-17'),
    template: 'development',
  },
  {
    id: '3',
    name: 'Brand Identity',
    description: 'Develop comprehensive brand identity and marketing materials',
    color: PROJECT_COLORS[2],
    status: 'active',
    priority: 'medium',
    progress: 80,
    startDate: new Date('2024-11-15'),
    endDate: new Date('2024-12-31'),
    owner: mockUsers[0],
    team: [mockUsers[0], mockUsers[4]],
    tasks: mockTasks.filter(task => task.projectId === '3'),
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-12-17'),
    template: 'marketing',
  },
  {
    id: '4',
    name: 'Q1 Product Launch',
    description: 'Coordinate product launch activities for Q1 2025',
    color: PROJECT_COLORS[3],
    status: 'active',
    priority: 'high',
    progress: 15,
    startDate: new Date('2024-12-15'),
    endDate: new Date('2025-03-31'),
    owner: mockUsers[0],
    team: [mockUsers[0], mockUsers[1], mockUsers[3], mockUsers[4]],
    tasks: [],
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-17'),
    template: 'event',
  },
];

// Mock Activity
export const mockActivity: ActivityItem[] = [
  {
    id: '1',
    type: 'task_completed',
    title: 'Task Completed',
    description: 'Setup project infrastructure completed by Michael Chen',
    user: mockUsers[1],
    timestamp: new Date('2024-12-17T10:30:00'),
    projectId: '2',
    taskId: '4',
  },
  {
    id: '2',
    type: 'comment_added',
    title: 'Comment Added',
    description: 'Sarah Johnson added a comment to "Design new landing page"',
    user: mockUsers[0],
    timestamp: new Date('2024-12-17T09:15:00'),
    projectId: '1',
    taskId: '1',
  },
  {
    id: '3',
    type: 'task_updated',
    title: 'Task Updated',
    description: 'Emily Rodriguez moved "Create brand guidelines" to review',
    user: mockUsers[2],
    timestamp: new Date('2024-12-17T08:45:00'),
    projectId: '3',
    taskId: '3',
  },
  {
    id: '4',
    type: 'project_created',
    title: 'Project Created',
    description: 'New project "Q1 Product Launch" created by Sarah Johnson',
    user: mockUsers[0],
    timestamp: new Date('2024-12-16T16:20:00'),
    projectId: '4',
  },
  {
    id: '5',
    type: 'user_joined',
    title: 'Team Member Joined',
    description: 'David Kim joined the Mobile App Development project',
    user: mockUsers[3],
    timestamp: new Date('2024-12-16T14:00:00'),
    projectId: '2',
  },
];

// Mock Dashboard Data
export const mockDashboard: Dashboard = {
  totalProjects: mockProjects.length,
  activeProjects: mockProjects.filter(p => p.status === 'active').length,
  completedTasks: mockTasks.filter(t => t.status === 'done').length,
  pendingTasks: mockTasks.filter(t => t.status !== 'done').length,
  teamMembers: mockUsers.length,
  recentActivity: mockActivity.slice(0, 5),
  upcomingDeadlines: mockTasks
    .filter(t => t.dueDate && t.status !== 'done')
    .sort((a, b) => a.dueDate!.getTime() - b.dueDate!.getTime())
    .slice(0, 5),
  projectProgress: mockProjects.map(project => ({
    project,
    progress: project.progress,
  })),
};